Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
rng = np.random.default_rng(2022)
fu = lambda x,noise: 0.5 * x + noise * rng.uniform(0,1,size=x.shape)

N = 100
x = rng.normal(10,5,size=(N,))
x_range = np.linspace(np.min(x),np.max(x),100)
y = f(x,0) # ground truth 
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [2][0m, in [0;36m<cell line: 8>[0;34m()[0m
[1;32m      6[0m x [38;5;241m=[39m rng[38;5;241m.[39mnormal([38;5;241m10[39m,[38;5;241m5[39m,size[38;5;241m=[39m(N,))
[1;32m      7[0m x_range [38;5;241m=[39m np[38;5;241m.[39mlinspace(np[38;5;241m.[39mmin(x),np[38;5;241m.[39mmax(x),[38;5;241m100[39m)
[0;32m----> 8[0m y [38;5;241m=[39m [43mf[49m(x,[38;5;241m0[39m)

[0;31mNameError[0m: name 'f' is not defined
NameError: name 'f' is not defined

